version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://poscaisse:caisse1234@localhost:5432/caissedb
      - JWT_SECRET=monSuperSecret
      - JWT_EXPIRES_IN=8h
      - PORT=3000
    volumes:
      - ./images:/app/images
